final Map<String, List<Map<String, String>>> countryContent = {
  'India': [
    {
      'backgroundImage': 'assets/images/indiaBG.png',
      //'boardImage': 'assets/images/indianCulture.png',
      'cloudText': 'India is vibrant, diverse, and rich in culture with colorful festivals, historic landmarks, and varied landscapes.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.4,0.9',
      'cloudAlignment': '-0.1,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG2.png',
      //'boardImage': 'assets/images/indianCulture.png',
      'cloudText': 'Let\'s see the culture of INDIA.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG2.png',
      'boardImage': 'assets/images/indianCulture.png',
      'cloudText': 'India is famous for its culture, cinema, and beautiful nature.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG2.png',
      'boardImage': 'assets/images/indiaLanguages.png',
      'cloudText': 'India has 22 languages.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG2.png',
      'boardImage': 'assets/images/indiaLanguages.png',
      'cloudText': 'Hindi is the main language.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG3.png',
      //'boardImage': 'assets/images/tiger.png',
      'cloudText': 'Lets see the animals of INDIA.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.3,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG3.png',
      'boardImage': 'assets/images/tiger.png',
      'cloudText': 'The national animal of India is tiger.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG3.png',
      'boardImage': 'assets/images/peacock.png',
      'cloudText': 'The national bird of India is peacock.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG4.png',
      //'boardImage': 'assets/images/khichdi.png',
      'cloudText': 'Lets see the food of INDIA.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.4,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG4.png',
      'boardImage': 'assets/images/khichdi.png',
      'cloudText': 'A popular Indian dish is khichdi.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG4.png',
      'boardImage': 'assets/images/biryani.png',
      'cloudText': 'Biryani is also popularized by Muslim communities.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG5.png',
      //'boardImage': 'assets/images/hockey.png',
      'cloudText': 'Lets see the sport of INDIA.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.3,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG5.png',
      'boardImage': 'assets/images/hockey.png',
      'cloudText': 'Hockey is a national sport in India.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG5.png',
      'boardImage': 'assets/images/SachinTendulkar.png',
      'cloudText': 'Sachin Tendulkar is known as the "God of Cricket."',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG6.png',
      //'boardImage': 'assets/images/diwali.png',
      'cloudText': 'Lets see the festivals of INDIA.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.4,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG6.png',
      'boardImage': 'assets/images/diwali.png',
      'cloudText': 'Diwali is a famous festival in India.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG6.png',
      'boardImage': 'assets/images/holi.png',
      'cloudText': 'Holi is also famous festival in India.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
  ],
  'USA': [
    {
      'backgroundImage': 'assets/images/usaWhiteHouse.png',
      //'boardImage': 'assets/images/English.png',
      'cloudText': 'The USA is a large and diverse country with a mix of natural landscapes, vibrant cities, and a rich cultural heritage',
      'characterImage': 'assets/images/usaGirl.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.4,0.9',
      'cloudAlignment': '-0.2,-0.4',
    },
    {
      'backgroundImage': 'assets/images/usaBG2.png',
      //'boardImage': 'assets/images/English.png',
      'cloudText': 'Lets see the culture of USA.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG2.png',
      'boardImage': 'assets/images/StatueofLiberty.png',
      'cloudText': 'The USA is famous for its cultural diversity, Hollywood, and iconic landmarks like the Statue of Liberty.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.4',
    },
    {
      'backgroundImage': 'assets/images/usaBG2.png',
      'boardImage': 'assets/images/English.png',
      'cloudText': 'The main language in the USA is English',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG2.png',
      //'boardImage': 'assets/images/English.png',
      'cloudText': 'Other languages spoken are Spanish and Chinese.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG3.png',
      //'boardImage': 'assets/images/baldEagle.png',
      'cloudText': 'Lets see the animals of USA.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG3.png',
      'boardImage': 'assets/images/baldEagle.png',
      'cloudText': 'The national bird of the USA is the bald eagle.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG3.png',
      'boardImage': 'assets/images/Bison.png',
      'cloudText': 'The national animal of the USA is the bison. ',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG4.png',
      //'boardImage': 'assets/images/baldEagle.png',
      'cloudText': 'Lets see the food of USA.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG4.png',
      'boardImage': 'assets/images/cheeseburger.png',
      'cloudText': 'A popular American dish is a cheeseburger.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/usaBG4.png',
      'boardImage': 'assets/images/barbecueRibs.png',
      'cloudText': 'Another popular dish is barbecue ribs.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/usaBG5.png',
      //'boardImage': 'assets/images/cheeseburger.png',
      'cloudText': 'Lets see the sport of USA.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.2',
    },
    {
      'backgroundImage': 'assets/images/usaBG5.png',
      'boardImage': 'assets/images/Baseball.png',
      'cloudText': 'Baseball is considered the national sport of the USA.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG5.png',
      'boardImage': 'assets/images/Basketball.png',
      'cloudText': 'Basketball was invented in the USA by James Naismith in 1891.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG6.png',
      //'boardImage': 'assets/images/baldEagle.png',
      'cloudText': 'Lets see the festivals of USA.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG5.png',
      'boardImage': 'assets/images/Thanksgiving.png',
      'cloudText': 'Thanksgiving is a famous tradition celebrated every November.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG5.png',
      'boardImage': 'assets/images/independenceDay.png',
      'cloudText': 'Independence Day, celebrated on July 4th, is a major tradition in the USA.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
  ],
  'Russia': [
    {
      'backgroundImage': 'assets/images/russiaBG.png',
      //'boardImage': 'assets/images/russianLanguage.png',
      'cloudText': 'Russia is the biggest country in the world',
      'characterImage': 'assets/images/russiaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG.png',
      //'boardImage': 'assets/images/russianLanguage.png',
      'cloudText': 'Lets see the culture of RUSSIA.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG2.png',
      'boardImage': 'assets/images/richHistory.png',
      'cloudText': 'Russia is famous for its vast landscapes, rich history, and cultural heritage.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG2.png',
      'boardImage': 'assets/images/russianLanguage.png',
      'cloudText': 'The main language in Russia is Russian.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG3.png',
      //'boardImage': 'assets/images/russianLanguage.png',
      'cloudText': 'Lets see the animals of RUSSIA.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG3.png',
      'boardImage': 'assets/images/brownBearRussia.png',
      'cloudText': 'The national animal of Russia is the brown bear.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG3.png',
      'boardImage': 'assets/images/double-headedEagle.png',
      'cloudText': 'The national bird is the double-headed eagle.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG4.png',
      //'boardImage': 'assets/images/double-headedEagle.png',
      'cloudText': 'Lets see the food of RUSSIA.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG4.png',
      'boardImage': 'assets/images/borscht.png',
      'cloudText': 'A popular Russian dish is borscht, a beet soup.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG4.png',
      'boardImage': 'assets/images/Pelmeni.png',
      'cloudText': 'Pelmeni (dumplings) is another popular dish in Russia.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG5.png',
      //'boardImage': 'assets/images/Pelmeni.png',
      'cloudText': 'Lets see the sport of RUSSIA.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG5.png',
      'boardImage': 'assets/images/iceHockey.png',
      'cloudText': 'Ice hockey is popular in Russia.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG5.png',
      'boardImage': 'assets/images/Chess.png',
      'cloudText': 'Chess is highly popular in Russia, with many grandmasters originating from the country.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG6.png',
      //'boardImage': 'assets/images/Chess.png',
      'cloudText': 'Lets see the festivals of RUSSIA',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG6.png',
      'boardImage': 'assets/images/Maslenitsa.png',
      'cloudText': 'Maslenitsa is a famous festival in Russia, celebrating the end of winter.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG6.png',
      'boardImage': 'assets/images/victoryDay.png',
      'cloudText': 'Victory Day (May 9) is a major holiday commemorating Russia\'s victory in World War II.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
  ],
  'Japan': [
    {
      'backgroundImage': 'assets/images/japanBG.png',
      //'boardImage': 'assets/images/japaneseLanguage.png',
      'cloudText': 'Japan is an island country known for its cool technology and old temples',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.5,0.9',
      'cloudAlignment': '0.3,-0.1',
    },
    {
      'backgroundImage': 'assets/images/japanBG2.png',
      //'boardImage': 'assets/images/japaneseLanguage.png',
      'cloudText': 'Lets see the culture of JAPAN.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.1,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG2.png',
      'boardImage': 'assets/images/Culture.png',
      'cloudText': 'Japanese people value traditions like tea ceremonies and martial arts.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/japanBG2.png',
      'boardImage': 'assets/images/japaneseLanguage.png',
      'cloudText': 'The main language in Japan is Japanese.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/japanBG3.png',
      //'boardImage': 'assets/images/japaneseLanguage.png',
      'cloudText': 'Lets see the animals of JAPAN.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.1,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG3.png',
      'boardImage': 'assets/images/Green Pheasant.png',
      'cloudText': 'The national bird of Japan is Green Pheasant.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG3.png',
      'boardImage': 'assets/images/JapaneseMacaque.png',
      'cloudText': 'The famous animal of Japan is the Japanese macaque.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG4.png',
      //'boardImage': 'assets/images/JapaneseMacaque.png',
      'cloudText': 'Lets see the food of JAPAN.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.1,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG4.png',
      'boardImage': 'assets/images/Sushi.png',
      'cloudText': 'A popular Japanese dish is Sushi.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG4.png',
      'boardImage': 'assets/images/Ramen.png',
      'cloudText': 'Ramen is another popular dish in Japan.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG5.png',
      //'boardImage': 'assets/images/Ramen.png',
      'cloudText': 'Lets see the sport of JAPAN.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.1,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG5.png',
      'boardImage': 'assets/images/Sumo.png',
      'cloudText': 'The national sport of Japan is sumo wrestling.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG5.png',
      'boardImage': 'assets/images/japanBaseball.png',
      'cloudText': 'Baseball is extremely popular in Japan, with many fans and professional teams.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG6.png',
      //'boardImage': 'assets/images/japanBaseball.png',
      'cloudText': 'Lets see the festivals of JAPAN.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.1,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG6.png',
      'boardImage': 'assets/images/Cherry Blossom Festiva.png',
      'cloudText': 'The Cherry Blossom Festival (Hanami) is a famous tradition in Japan.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG6.png',
      'boardImage': 'assets/images/tanabata japan.png',
      'cloudText': 'Tanabata is another famous festival, celebrating the meeting of two stars.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
  ],
  'United Kingdom': [
    {
      'backgroundImage': 'assets/images/ukBG.png',
      //'boardImage': 'assets/images/English.png',
      'cloudText': 'The UK is famous for its monarchy, history, and iconic landmarks like Big Ben and Stonehenge.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.5,0.9',
      'cloudAlignment': '0.3,-0.4',
    },
    {
      'backgroundImage': 'assets/images/ukBG.png',
      'boardImage': 'assets/images/English.png',
      'cloudText': 'The main language of the UK is English.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,0.9',
      'cloudAlignment': '0.3,-0.1',
    },
    {
      'backgroundImage': 'assets/images/ukBG3.png',
      'cloudText': 'Lets see the animals of United Kingdom.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      //'characterAlignment': '-0.1,0.9',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/ukBG3.png',
      'boardImage': 'assets/images/Lion.png',
      'cloudText': 'The national animal of the UK is the lion.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/ukBG3.png',
      'boardImage': 'assets/images/Robin.png',
      'cloudText': 'The national bird is the European Robin.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/ukBG4.png',
      //'boardImage': 'assets/images/English.png',
      'cloudText': 'Lets see the food of United Kingdom.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/ukBG4.png',
      'boardImage': 'assets/images/Fish&Chips.png',
      'cloudText': 'Fish and chips is a classic British dish.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/ukBG4.png',
      'boardImage': 'assets/images/SundayRoast.png',
      'cloudText': 'Another popular dish is the Sunday roast.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/indiaBG5.png',
      'boardImage': 'assets/images/ukFootball.png',
      'cloudText': 'The UK doesn’t have an official national sport, but football is the most popular.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/indiaBG5.png',
      'boardImage': 'assets/images/WimbledonTennis.png',
      'cloudText': 'Wimbledon is the oldest tennis tournament in the world, held annually in London.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/ukBG5.png',
      //'boardImage': 'assets/images/English.png',
      'cloudText': 'Lets see the festivals of United Kingdom.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.25,-0.35',
    },
    {
      'backgroundImage': 'assets/images/ukBG5.png',
      'boardImage': 'assets/images/BonfireNight.png',
      'cloudText': 'Bonfire Night is a famous tradition celebrated every November.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/ukBG5.png',
      'boardImage': 'assets/images/BigBen.png',
      'cloudText': 'The Changing of the Guard at Buckingham Palace is a popular tradition.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
  ],
  'Italy': [
    {
      'backgroundImage': 'assets/images/italyBG.png',
      //'boardImage': 'assets/images/italyArchitecture.png',
      'cloudText': 'Italy is famous for its art, architecture, and delicious cuisine, especially pasta and pizza.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.5,0.8',
      'cloudAlignment': '0.4,-0.6',
    },
    {
      'backgroundImage': 'assets/images/italyBG2.jpg',
      'boardImage': 'assets/images/ItalianLanguage.png',
      'cloudText': 'The main language spoken in Italy is Italian.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,0.9',
      'cloudAlignment': '0.4,-0.4',
    },
    {
      'backgroundImage': 'assets/images/italyBG3.png',
      //'boardImage': 'assets/images/ItalianLanguage.png',
      'cloudText': 'Lets see the animals of Italy.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG3.png',
      'boardImage': 'assets/images/italianWolf.png',
      'cloudText': 'The national animal of Italy is the Italian wolf.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,1',
      'cloudAlignment': '0.5,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG3.png',
      'boardImage': 'assets/images/Italian sparrow.png',
      'cloudText': 'The national bird of Italy is the Italian sparrow.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,1',
      'cloudAlignment': '0.5,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG4.jpg',
      //'boardImage': 'assets/images/ItalianLanguage.png',
      'cloudText': 'Lets see the food of Italy.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG4.jpg',
      'boardImage': 'assets/images/pastaCarbonara.png',
      'cloudText': 'One popular Italian dish is pasta carbonara.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG4.jpg',
      'boardImage': 'assets/images/risotto.png',
      'cloudText': 'Another popular dish is risotto.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      //'boardImage': 'assets/images/ItalianLanguage.png',
      'cloudText': 'Lets see the sport of Italy.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'boardImage': 'assets/images/italyFootball.png',
      'cloudText': 'Football (soccer) is the most popular sport in Italy.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.35',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'boardImage': 'assets/images/FIFAWorldCup.png',
      'cloudText': 'Italy has won four FIFA World Cup titles in football.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.35',
    },
    {
      'backgroundImage': 'assets/images/italyBG6.png',
      //'boardImage': 'assets/images/ItalianLanguage.png',
      'cloudText': 'Lets see the festivals of Italy.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.25,-0.35',
    },
    {
      'backgroundImage': 'assets/images/italyBG6.png',
      'boardImage': 'assets/images/CarnivalofVenice.png',
      'cloudText': 'Carnival of Venice is a famous Italian festival known for its masks.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.35',
    },
    {
      'backgroundImage': 'assets/images/italyBG6.png',
      'boardImage': 'assets/images/horseRace.png',
      'cloudText': 'The Palio di Siena, a horse race, is another famous tradition in Italy.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.35',
    },
  ],
  'Kenya': [
    {
      'backgroundImage': 'assets/images/kenyaBG.png',
      'boardImage': 'assets/images/wildlifeSafaris.png',
      'cloudText': 'Kenya is famous for its wildlife safaris and the Masai Mara.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,0.9',
      'cloudAlignment': '0.3,-0.4',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG2.png',
      'boardImage': 'assets/images/Swahili.png',
      'cloudText': 'Kenya has two official languages: Swahili and English.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,0.9',
      'cloudAlignment': '0.3,-0.1',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG3.png',
      //'boardImage': 'assets/images/Lion.png',
      'cloudText': 'Lets see the animals of Kenya.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG3.png',
      'boardImage': 'assets/images/Lion.png',
      'cloudText': 'The national animal of Kenya is the lion.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG3.png',
      'boardImage': 'assets/images/lilac-breasted roller.png',
      'cloudText': 'The national bird is the lilac-breasted roller.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG4.png',
      //'boardImage': 'assets/images/English.png',
      'cloudText': 'Lets see the food of Kenya.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG4.png',
      'boardImage': 'assets/images/kenyanUgali.png',
      'cloudText': 'A popular Kenyan dish is ugali, a maize flour porridge.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG4.png',
      'boardImage': 'assets/images/nyamaChoma.png',
      'cloudText': 'Nyama choma (grilled meat) is another popular dish.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      //'boardImage': 'assets/images/English.png',
      'cloudText': 'Lets see the sport of Kenya.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'boardImage': 'assets/images/Athletics.png',
      'cloudText': 'Athletics, especially long-distance running, is the most popular sport.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'boardImage': 'assets/images/internationalMarathons.png',
      'cloudText': 'Kenyan athletes dominate international marathons and distance running events.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG2.png',
      //'boardImage': 'assets/images/English.png',
      'cloudText': 'Lets see the festivals of Italy.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.25,-0.35',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG2.png',
      'boardImage': 'assets/images/MaasaiMaraMigration.png',
      'cloudText': 'The Masai Mara Migration is a significant wildlife event.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG2.png',
      'boardImage': 'assets/images/lamu.png',
      'cloudText': 'The Lamu Cultural Festival showcases traditional Swahili culture.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
  ],
  'Brazil': [
    {
      'backgroundImage': 'assets/images/brazilBG.png',
      'boardImage': 'assets/images/amazonRainforestBrazil.png',
      'cloudText': 'Brazil is famous for its Amazon rainforest, carnival, and football.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.5,0.9',
      'cloudAlignment': '0.3,-0.4',
    },
    {
      'backgroundImage': 'assets/images/brazilBG2.png',
      'boardImage': 'assets/images/Portuguese.png',
      'cloudText': 'The main language spoken in Brazil is Portuguese.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,0.9',
      'cloudAlignment': '0.3,-0.1',
    },
    {
      'backgroundImage': 'assets/images/brazilBG3.png',
      //'boardImage': 'assets/images/Portuguese.png',
      'cloudText': 'Lets see the animals of Brazil.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/brazilBG3.png',
      'boardImage': 'assets/images/Jaguar.png',
      'cloudText': 'The national animal of Brazil is the jaguar.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG3.png',
      'boardImage': 'assets/images/rufous-belliedThrush.png',
      'cloudText': 'The national bird of Brazil is the rufous-bellied thrush.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/indiaBG4.png',
      //'boardImage': 'assets/images/Portuguese.png',
      'cloudText': 'Lets see the food of Brazil.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG4.png',
      'boardImage': 'assets/images/Feijoada.png',
      'cloudText': 'Feijoada, a black bean stew, is a popular dish.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/indiaBG4.png',
      'boardImage': 'assets/images/Churrasco.png',
      'cloudText': 'Churrasco, Brazilian barbecue, is also well-known.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      //'boardImage': 'assets/images/Portuguese.png',
      'cloudText': 'Lets see the sport of Brazil.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'boardImage': 'assets/images/brazilFootball.png',
      'cloudText': 'Football (soccer) is Brazil\'s national and most popular sport.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'boardImage': 'assets/images/worldcup.png',
      'cloudText': 'Brazil has won the FIFA World Cup five times, more than any other country.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/brazilBG4.png',
      //'boardImage': 'assets/images/Portuguese.png',
      'cloudText': 'Lets see the festivals of Brazil.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.25,-0.35',
    },
    {
      'backgroundImage': 'assets/images/brazilBG4.png',
      'boardImage': 'assets/images/Carnival.png',
      'cloudText': 'Carnival is the most famous festival in Brazil.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/brazilBG4.png',
      'boardImage': 'assets/images/festaJunina.png',
      'cloudText': 'Festa Junina is another popular Brazilian tradition.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
  ],
  'China': [
    {
      'backgroundImage': 'assets/images/chinaBG.png',
      'boardImage': 'assets/images/Great Wall.png',
      'cloudText': 'China is famous for its Great Wall, ancient history, and cultural heritage.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.5,0.9',
      'cloudAlignment': '0.3,-0.4',
    },
    {
      'backgroundImage': 'assets/images/chinaBG.png',
      'boardImage': 'assets/images/chineseLanguage.png',
      'cloudText': 'The main language of China is Mandarin Chinese.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,0.9',
      'cloudAlignment': '0.3,-0.1',
    },
    {
      'backgroundImage': 'assets/images/chinaBG2.png',
      //'boardImage': 'assets/images/chineseLanguage.png',
      'cloudText': 'Lets see the animals of China.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/chinaBG2.png',
      'boardImage': 'assets/images/Giant Panda.png',
      'cloudText': 'The national animal of China is the giant panda.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/chinaBG2.png',
      'boardImage': 'assets/images/red-crowned crane.png',
      'cloudText': 'The national bird of China is the red-crowned crane.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.75,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/chinaBG5.png',
      //'boardImage': 'assets/images/chineseLanguage.png',
      'cloudText': 'Lets see the food of China.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/chinaBG5.png',
      'boardImage': 'assets/images/Peking duck.png',
      'cloudText': 'Peking duck is a popular dish in China.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/chinaBG5.png',
      'boardImage': 'assets/images/Dis sum.png',
      'cloudText': 'Dim sum is also a well-loved traditional dish.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/chinaBG3.png',
      //'boardImage': 'assets/images/chineseLanguage.png',
      'cloudText': 'Lets see the sport of China.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/chinaBG3.png',
      'boardImage': 'assets/images/Table tennis.png',
      'cloudText': 'Table tennis is considered the national sport of China.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/chinaBG3.png',
      'boardImage': 'assets/images/tableTennis-Olympic.png',
      'cloudText': 'China consistently dominates the sport of table tennis at the Olympics.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/chinaBG4.png',
      //'boardImage': 'assets/images/chineseLanguage.png',
      'cloudText': 'Lets see the festivals of China.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.25,-0.35',
    },
    {
      'backgroundImage': 'assets/images/chinaBG4.png',
      'boardImage': 'assets/images/ChineseNewYear.png',
      'cloudText': 'The Chinese New Year, also known as Spring Festival, is the most famous festival.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/chinaBG4.png',
      'boardImage': 'assets/images/Mid-AutumnFestival.png',
      'cloudText': 'The Mid-Autumn Festival is another important celebration in China.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
  ]
};
