final Map<String, List<Map<String, String>>> countryContent = {
  'India': [
    {
      'backgroundImage': 'assets/images/indiaBG.png',
      'cloudText': 'India is vibrant, diverse, and rich in culture with colorful festivals, historic landmarks, and varied landscapes.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.4,0.9',
      'cloudAlignment': '-0.1,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG2.png',
      'cloudText': 'Let\'s see the culture of INDIA.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG2.png',
      'cloudText':
          'India is famous for its culture, cinema, and beautiful nature.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG2.png',
      'cloudText': 'India has 22 languages.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG2.png',
      'cloudText': 'Hindi is the main language.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG3.png',
      'cloudText': 'Lets see the animals of INDIA.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.3,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG3.png',
      'cloudText': 'The national animal of India is tiger.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG3.png',
      'cloudText': 'The national bird of India is peacock.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG4.png',
      'cloudText': 'Lets see the food of INDIA.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.4,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG4.png',
      'cloudText': 'A popular Indian dish is khichdi.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG5.png',
      'cloudText': 'Lets see the sport of INDIA.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.3,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG5.png',
      'cloudText': 'Hockey is a national sport in India.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG5.png',
      'cloudText': 'Sachin Tendulkar is known as the "God of Cricket."',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG6.png',
      'cloudText': 'Lets see the festivals of INDIA.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.4,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG6.png',
      'cloudText': 'Diwali is a famous festival in India.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG6.png',
      'cloudText': 'Holi is also famous festival in India.',
      'characterImage': 'assets/images/ladyInSaree.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
  ],
  'USA': [
    {
      'backgroundImage': 'assets/images/usaWhiteHouse.png',
      'cloudText':
          'The USA is a large and diverse country with a mix of natural landscapes, vibrant cities, and a rich cultural heritage',
      'characterImage': 'assets/images/usaGirl.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.5,0.9',
      'cloudAlignment': '-0.2,-0.4',
    },
    {
      'backgroundImage': 'assets/images/usaBG2.png',
      'cloudText': 'Lets see the culture of USA.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG2.png',
      'cloudText':
          'The USA is a large and diverse country with a mix of natural landscapes, vibrant cities, and a rich cultural heritage.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.4',
    },
    {
      'backgroundImage': 'assets/images/usaBG2.png',
      'cloudText': 'The main language in the USA is English',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG2.png',
      'cloudText': 'Other languages spoken are Spanish and Chinese.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG3.png',
      'cloudText': 'Lets see the animals of USA.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG3.png',
      'cloudText': 'The national animal of the USA is the bald eagle.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG3.png',
      'cloudText': 'The national mammal is the bison.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG4.png',
      'cloudText': 'Lets see the food of USA.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG4.png',
      'cloudText': 'Lets see the food of USA.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG4.png',
      'cloudText': 'Hotdog',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/usaBG5.png',
      'cloudText': 'Lets see the sport of USA.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.2',
    },
    {
      'backgroundImage': 'assets/images/usaBG5.png',
      'cloudText': 'Tom Brady has won 7 Super Bowl titles.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG5.png',
      'cloudText':
          'Basketball is also popular. Michael Jordan has 6 NBA Finals MVP awards.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/usaBG6.png',
      'cloudText': 'Lets see the festivals of USA.',
      'characterImage': 'assets/images/usaGirl2.png',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
  ],
  'Russia': [
    {
      'backgroundImage': 'assets/images/russiaBG.png',
      'cloudText': 'Russia is the biggest country in the world',
      'characterImage': 'assets/images/russiaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      //'characterAlignment': '-0.1,1',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG.png',
      'cloudText': 'Lets see the culture of RUSSIA.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG2.png',
      'cloudText': 'Russians love reading, dancing, and have beautiful churches.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG2.png',
      'cloudText': 'The main language in Russia is Russian.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG2.png',
      'cloudText': 'Other languages include Tatar and Bashkir.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG3.png',
      'cloudText': 'Lets see the animals of RUSSIA.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG3.png',
      'cloudText': 'The national animal of Russia is the brown bear.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG3.png',
      'cloudText': 'The national animal of Russia is the brown bear.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG4.png',
      'cloudText': 'Lets see the food of RUSSIA.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG4.png',
      'cloudText': 'A popular Russian dish is borscht, a beet soup.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG4.png',
      'cloudText': 'Pelmeni',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG5.png',
      'cloudText': 'Lets see the sport of RUSSIA.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG5.png',
      'cloudText': 'Ice hockey is popular in Russia.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG5.png',
      'cloudText': 'Figure skating is also popular.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG6.png',
      'cloudText': 'Lets see the festivals of RUSSIA',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '0,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/russiaBG6.png',
      'cloudText':
          'Maslenitsa is a festival that celebrates the end of winter.',
      'characterImage': 'assets/images/russiaGirl2.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,1',
      'cloudAlignment': '-0.6,-0.1',
    },
  ],
  'Japan': [
    {
      'backgroundImage': 'assets/images/japanBG.png',
      'cloudText': 'Japan is an island country known for its cool technology and old temples',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.5,0.9',
      'cloudAlignment': '0.3,-0.1',
    },
    {
      'backgroundImage': 'assets/images/japanBG2.png',
      'cloudText': 'Lets see the culture of JAPAN.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.1,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG2.png',
      'cloudText':
          'Japanese people value traditions like tea ceremonies and martial arts.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/japanBG2.png',
      'cloudText': 'The main language in Japan is Japanese.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/japanBG2.png',
      'cloudText': 'They also enjoy drawing and cartoons.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.1',
    },
    {
      'backgroundImage': 'assets/images/japanBG3.png',
      'cloudText': 'Lets see the animals of JAPAN.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.1,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG3.png',
      'cloudText': 'The national bird of Japan is Green Pheasant.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG3.png',
      'cloudText': 'The national fish of Japan is koi carp.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG4.png',
      'cloudText': 'Lets see the food of JAPAN.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.1,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG4.png',
      'cloudText': 'A popular Japanese dish is Sushi.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG4.png',
      'cloudText': 'Udon is also a popular dish in Japan.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG5.png',
      'cloudText': 'Lets see the sport of JAPAN.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.1,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG5.png',
      'cloudText': 'Baseball is very popular in Japan.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG5.png',
      'cloudText': 'Judo is also well-known.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG6.png',
      'cloudText': 'Lets see the festivals of JAPAN.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.1,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG6.png',
      'cloudText': 'Cherry Blossom is famous Festival in JAPAN.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
    {
      'backgroundImage': 'assets/images/japanBG6.png',
      'cloudText': 'Gion Matsuri Festival is also famous in JAPAN.',
      'characterImage': 'assets/images/japanGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.2',
    },
  ],
  'United Kingdom': [
    {
      'backgroundImage': 'assets/images/ukBG.png',
      'cloudText':
          'The UK is famous for its monarchy, history, and iconic landmarks like Big Ben and Stonehenge.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.5,0.9',
      'cloudAlignment': '0.3,-0.4',
    },
    {
      'backgroundImage': 'assets/images/ukBG.png',
      'cloudText': 'The main language of the UK is English.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.5,0.9',
      'cloudAlignment': '0.3,-0.1',
    },
    {
      'backgroundImage': 'assets/images/ukBG3.png',
      'cloudText': 'Lets see the animals of United Kingdom.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/ukBG3.png',
      'cloudText': 'The national animal of the UK is the lion.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.65,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/ukBG3.png',
      'cloudText': 'The national bird is the European Robin.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.65,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/ukBG4.png',
      'cloudText': 'Lets see the food of United Kingdom.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/ukBG4.png',
      'cloudText': 'Fish and chips is a classic British dish.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/ukBG4.png',
      'cloudText': 'Another popular dish is the Sunday roast.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/indiaBG5.png',
      'cloudText':
          'The UK doesn’t have an official national sport, but football is the most popular.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/indiaBG5.png',
      'cloudText':
          'Wimbledon is the oldest tennis tournament in the world, held annually in London.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/ukBG5.png',
      'cloudText': 'Lets see the festivals of United Kingdom.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.25,-0.35',
    },
    {
      'backgroundImage': 'assets/images/ukBG5.png',
      'cloudText':
          'Bonfire Night is a famous tradition celebrated every November.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/ukBG5.png',
      'cloudText':
          'The Changing of the Guard at Buckingham Palace is a popular tradition.',
      'characterImage': 'assets/images/ukBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
  ],
  'Italy': [
    {
      'backgroundImage': 'assets/images/italyBG.png',
      'cloudText':
          'Italy is famous for its art, architecture, and delicious cuisine, especially pasta and pizza.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.7,0.8',
      'cloudAlignment': '0.4,-0.6',
    },
    {
      'backgroundImage': 'assets/images/italyBG2.jpg',
      'cloudText': 'The main language spoken in Italy is Italian.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.7,0.9',
      'cloudAlignment': '0.4,-0.4',
    },
    {
      'backgroundImage': 'assets/images/italyBG3.png',
      'cloudText': 'Lets see the animals of Italy.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG3.png',
      'cloudText': 'The national animal of Italy is the Italian wolf.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.8,1',
      'cloudAlignment': '0.5,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG3.png',
      'cloudText': 'The national bird of Italy is the Italian sparrow.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.8,1',
      'cloudAlignment': '0.5,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG4.jpg',
      'cloudText': 'Lets see the food of Italy.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG4.jpg',
      'cloudText': 'One popular Italian dish is pasta carbonara.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG4.jpg',
      'cloudText': 'Another popular dish is risotto.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'cloudText': 'Lets see the sport of Italy.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'cloudText': 'Football (soccer) is the most popular sport in Italy.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.35',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'cloudText': 'Italy has won four FIFA World Cup titles in football.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.35',
    },
    {
      'backgroundImage': 'assets/images/italyBG6.png',
      'cloudText': 'Lets see the festivals of Italy.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.25,-0.35',
    },
    {
      'backgroundImage': 'assets/images/italyBG6.png',
      'cloudText':
          'Carnival of Venice is a famous Italian festival known for its masks.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.35',
    },
    {
      'backgroundImage': 'assets/images/italyBG6.png',
      'cloudText':
          'The Palio di Siena, a horse race, is another famous tradition in Italy.',
      'characterImage': 'assets/images/italyBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.35',
    },
  ],
  'Kenya': [
    {
      'backgroundImage': 'assets/images/kenyaBG.png',
      'cloudText':
          'Kenya is famous for its wildlife safaris and the Masai Mara.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.5,0.9',
      'cloudAlignment': '0.3,-0.4',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG2.png',
      'cloudText': 'Kenya has two official languages: Swahili and English.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.5,0.9',
      'cloudAlignment': '0.3,-0.1',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG3.png',
      'cloudText': 'Lets see the animals of Kenya.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG3.png',
      'cloudText': 'The national animal of Kenya is the lion.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.65,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG3.png',
      'cloudText': 'The national bird is the lilac-breasted roller.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.65,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG4.png',
      'cloudText': 'Lets see the food of Kenya.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG4.png',
      'cloudText': 'A popular Kenyan dish is ugali, a maize flour porridge.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG4.png',
      'cloudText': 'Nyama choma (grilled meat) is another popular dish.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'cloudText': 'Lets see the sport of Kenya.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'cloudText':
          'Athletics, especially long-distance running, is the most popular sport.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'cloudText':
          'Kenyan athletes dominate international marathons and distance running events.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG2.png',
      'cloudText': 'Lets see the festivals of Italy.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.25,-0.35',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG2.png',
      'cloudText': 'The Masai Mara Migration is a significant wildlife event.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG2.png',
      'cloudText':
          'The Lamu Cultural Festival showcases traditional Swahili culture.',
      'characterImage': 'assets/images/kenyaBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
  ],
  'Brazil': [
    {
      'backgroundImage': 'assets/images/brazilBG.png',
      'cloudText':
          'Brazil is famous for its Amazon rainforest, carnival, and football.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.5,0.9',
      'cloudAlignment': '0.3,-0.4',
    },
    {
      'backgroundImage': 'assets/images/brazilBG2.png',
      'cloudText': 'The main language spoken in Brazil is Portuguese.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.5,0.9',
      'cloudAlignment': '0.3,-0.1',
    },
    {
      'backgroundImage': 'assets/images/brazilBG3.png',
      'cloudText': 'Lets see the animals of Brazil.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/brazilBG3.png',
      'cloudText': 'The national animal of Brazil is the jaguar.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.65,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/kenyaBG3.png',
      'cloudText': 'The national bird of Brazil is the rufous-bellied thrush.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.65,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/indiaBG4.png',
      'cloudText': 'Lets see the food of Brazil.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/indiaBG4.png',
      'cloudText': 'Feijoada, a black bean stew, is a popular dish.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/indiaBG4.png',
      'cloudText': 'Churrasco, Brazilian barbecue, is also well-known.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'cloudText': 'Lets see the sport of Brazil.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'cloudText':
          'Football (soccer) is Brazil\'s national and most popular sport.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/italyBG5.png',
      'cloudText':
          'Brazil has won the FIFA World Cup five times, more than any other country.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/brazilBG4.png',
      'cloudText': 'Lets see the festivals of Brazil.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.25,-0.35',
    },
    {
      'backgroundImage': 'assets/images/brazilBG4.png',
      'cloudText': 'Carnival is the most famous festival in Brazil.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/brazilBG4.png',
      'cloudText': 'Festa Junina is another popular Brazilian tradition.',
      'characterImage': 'assets/images/brazilBoy.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
  ],
  'China': [
    {
      'backgroundImage': 'assets/images/chinaBG.png',
      'cloudText':
          'China is famous for its Great Wall, ancient history, and cultural heritage.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.5,0.9',
      'cloudAlignment': '0.3,-0.4',
    },
    {
      'backgroundImage': 'assets/images/chinaBG.png',
      'cloudText': 'The main language of China is Mandarin Chinese.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.5,0.9',
      'cloudAlignment': '0.3,-0.1',
    },
    {
      'backgroundImage': 'assets/images/chinaBG2.png',
      'cloudText': 'Lets see the animals of China.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/chinaBG2.png',
      'cloudText': 'The national animal of China is the giant panda.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.65,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/chinaBG2.png',
      'cloudText': 'The national bird of China is the red-crowned crane.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud2.png',
      'characterAlignment': '0.65,1',
      'cloudAlignment': '0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/chinaBG5.png',
      'cloudText': 'Lets see the food of China.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/chinaBG5.png',
      'cloudText': 'Peking duck is a popular dish in China.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/chinaBG5.png',
      'cloudText': 'Dim sum is also a well-loved traditional dish.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.5,-0.2',
    },
    {
      'backgroundImage': 'assets/images/chinaBG3.png',
      'cloudText': 'Lets see the sport of China.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.2,-0.1',
    },
    {
      'backgroundImage': 'assets/images/chinaBG3.png',
      'cloudText': 'Table tennis is considered the national sport of China.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/chinaBG3.png',
      'cloudText':
          'China consistently dominates the sport of table tennis at the Olympics.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/chinaBG4.png',
      'cloudText': 'Lets see the festivals of China.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.1,0.9',
      'cloudAlignment': '0.25,-0.35',
    },
    {
      'backgroundImage': 'assets/images/chinaBG4.png',
      'cloudText':
          'The Chinese New Year, also known as Spring Festival, is the most famous festival.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
    {
      'backgroundImage': 'assets/images/chinaBG4.png',
      'cloudText':
          'The Mid-Autumn Festival is another important celebration in China.',
      'characterImage': 'assets/images/chinaGirl.gif',
      'cloudImage': 'assets/images/Cloud.png',
      'characterAlignment': '-0.75,0.9',
      'cloudAlignment': '-0.6,-0.35',
    },
  ]
};
